"""Initial migration with all tables

Revision ID: 36610c554209
Revises: 
Create Date: 2025-07-28 16:26:15.011228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36610c554209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=True),
    sa.Column('sport_type', sa.Enum('Cricket', 'Football', name='sporttype'), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('coach_role', sa.Enum('CricketCoach', 'FootballCoach', name='coachroleenum'), nullable=True),
    sa.Column('coach_speciality', sa.String(length=100), nullable=True),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('player_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport_type', sa.Enum('Cricket', 'Football', name='sporttype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('admin_role', sa.Enum('SuperAdmin', 'Moderator', 'Support', name='adminroleenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('sport_type', sa.Enum('Cricket', 'Football', name='sporttype'), nullable=True),
    sa.Column('player_role_id', sa.Integer(), nullable=False),
    sa.Column('dominant_hand', sa.String(length=10), nullable=True),
    sa.Column('batting_style', sa.String(length=50), nullable=True),
    sa.Column('bowling_style', sa.String(length=50), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('instagram_link', sa.String(length=255), nullable=True),
    sa.Column('facebook_link', sa.String(length=255), nullable=True),
    sa.Column('twitter_link', sa.String(length=255), nullable=True),
    sa.Column('youtube_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['player_role_id'], ['player_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('super_admins')
    op.drop_table('player_roles')
    op.drop_table('coaches')
    # ### end Alembic commands ###
